plugins { id 'com.android.application' }

android {
    namespace 'com.jlxc.a4ldashboard'
    compileSdk 34

    defaultConfig {
        applicationId 'com.jlxc.a4ldashboard'
        minSdk 23
        targetSdk 28
        versionCode 1
        versionName '0.1.0-alpha'
    }

    buildFeatures { aidl true }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
