plugins { id 'com.android.application' }

android {
    namespace 'com.jlxc.mikucarlauncher'
    compileSdk 34

    defaultConfig {
        applicationId 'com.jlxc.mikucarlauncher'
        minSdk 23
        targetSdk 28
        versionCode 1
        versionName '0.1.0-sidebar-ui'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
